version: '3.8'

services:
  scanner-app:
    image: scanner-mini-app
    deploy: 
      mode: global
      restart_policy:
        condition: on-failure
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
    ports:
      - published: 3000
        target: 80
        protocol: tcp
        mode: ingress
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
