version: '3.8'

services:
  scanner-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    container_name: scanner-mini-app
    ports:
      - "${PORT:-3000}:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - scanner-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  scanner-network:
    driver: bridge